### ISSUE TITLE
[6D teleop] pygame

### ISSUE THREAD

**Issue by jschleicher** [PilzDE/pilz_teach#17]
Switch implemantation to pygame

**Comment by DamKoVosh** [comment]
Problem with pygame is, it does not have a headless mode, at least not for keyboard interaction. So we  would need to have a window with focus. Since this is not our current goal, we will not take pygame for the moment.
Searching and Evaluating alternatives at the moment

**Comment by DamKoVosh** [comment]
The only working possible solution i can find is: pynput
This works with pressing and releasing keys, so all currently pressed keys can be figuered out.
This also has a rosdep, so that would not be the problem

However:
```
On Linux, pynput uses X, so the following must be true:

-  An X server must be running.
-  The environment variable $DISPLAY must be set.

The latter requirement means that running pynput over SSH generally will not work. To work around that, make sure to set $DISPLAY:

$ DISPLAY=:0 python -c 'import pynput'
```

So we would have ssh limitations. Not sure if running jogging above ssh is imporend for us...

**Comment by jschleicher** [comment]
Closing as described above and in #28
